name: CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  # ============================================================
  # CI - BUILD AND PUSH
  # ============================================================
  build-and-push:

    name: CI - Build and Push

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOC_USERNAME }}
          password: ${{ secrets.DOC_PWD }}


      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOC_USERNAME }}/githubactions:latest \
            -t ${{ secrets.DOC_USERNAME }}/githubactions:${{ github.sha }} \
            .


      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOC_USERNAME }}/githubactions:latest
          docker push ${{ secrets.DOC_USERNAME }}/githubactions:${{ github.sha }}


  # ============================================================
  # CD - DEPLOY TO KUBERNETES
  # ============================================================
  deploy:

    name: CD - Deploy to Kubernetes

    needs: build-and-push

    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # --------------------------------------------------------
      # Install kubectl
      # --------------------------------------------------------
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest


      # --------------------------------------------------------
      # Configure kubeconfig
      # --------------------------------------------------------
      - name: Configure Kubernetes
        env:
          KUBE_CONFIG: ${{ secrets.KILLERCODA_SSH_KEY }}

        run: |
          mkdir -p $HOME/.kube

          printf '%s' "$KILLERCODA_SSH_KEY" > ~/.kube/config
          cat<<EOF>> $HOME/.kube/config
          ${{secrets.KILLERCODA_SSH_KEY}}
          EOF
          

          chmod 600 $HOME/.kube/config


      # --------------------------------------------------------
      # Verify Kubernetes connection
      # --------------------------------------------------------
      - name: Check Kubernetes Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes


      # --------------------------------------------------------
      # Apply Kubernetes manifests
      # --------------------------------------------------------
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml


      # --------------------------------------------------------
      # Deploy exact GitHub commit image
      # --------------------------------------------------------
      - name: Update Application Image
        run: |
          kubectl set image deployment/cicd-app \
            my-app=${{ secrets.DOC_USERNAME }}/githubactions:${{ github.sha }}


      # --------------------------------------------------------
      # Wait for rollout
      # --------------------------------------------------------
      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/cicd-app --timeout=180s


      # --------------------------------------------------------
      # Verify
      # --------------------------------------------------------
      - name: Verify Deployment
        run: |
          kubectl get deployment cicd-app
          kubectl get pods -l app=cicd-app
          kubectl get service cicd-service
