name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOC_PWD }}" | docker login \
          -u "${{ secrets.DOC_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOC_USERNAME }}/github-actions-docker:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOC_USERNAME }}/github-actions-docker:latest

      - name: Deploy to Kubernetes (Killercoda)
        run: |
          echo "${{ secrets.KILLERCODA_SSH_KEY }}" > killercoda.pem
          chmod 600 killercoda.pem

          ssh -o StrictHostKeyChecking=no \
            -i killercoda.pem \
            root@${{ secrets.KILLERCODA_HOST }} << EOF

          docker login -u "${{ secrets.DOC_USERNAME }}" -p "${{ secrets.DOC_PWD }}"
          docker pull ${{ secrets.DOC_USERNAME }}/github-actions-docker:latest

          kubectl delete deployment github-actions-docker --ignore-not-found=true
          kubectl delete service github-actions-docker --ignore-not-found=true

          kubectl create deployment github-actions-docker \
            --image=${{ secrets.DOC_USERNAME }}/github-actions-docker:latest

          kubectl expose deployment github-actions-docker \
            --type=NodePort --port=80 --target-port=80

          kubectl rollout status deployment/github-actions-docker

          EOF

          rm -f killercoda.pem
