name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOC_PWD }}" | \
          docker login -u "${{ secrets.DOC_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOC_USERNAME }}/github-actions-docker:latest .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOC_USERNAME }}/github-actions-docker:latest
